POST http://localhost:3003/user/create/
Content-Type: application/json

{
    "name": "Jenifer Kindermann",
    "email": "jenifer@email.com.br",
    "password": "shdiauhiufoeijpw"
}

######

POST http://localhost:3003/user/create/
Content-Type: application/json

{
    "name": "Akin Kindermann",
    "email": "akin@email.com.br",
    "password": "iwueuhwosdkjhiu"
}

######

POST http://localhost:3003/post/create/
Content-Type: application/json

{
    "photo": "Foto 2",
    "description": "foto na praia",
    "type": "event",
    "authorId": "0989c5b8-df60-4b4a-9591-1e9b35c53005"
    
}